# Generated by Django 4.0.3 on 2022-03-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0002_rename_aler_ego_supers_alter_ego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='super_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_types.super_types'),
            preserve_default=False,
        ),
    ]
